import {ArrowRight,ArrowUpRight,BookOpen,ClipboardList,Clock3,CheckCircle2,FileText} from 'lucide-react'
import type {AssignmentDetail,CourseSummary,UserSummary} from '../../lib/contracts'
export function date(value:string){return new Date(value).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}
export function Badge({assignment}:{assignment:AssignmentDetail}){const sub=assignment.my_submission;const text=sub?.grade?.published_at?'已反馈':sub?'已提交':assignment.status==='closed'?'已关闭':new Date(assignment.deadline)<new Date()?'已截止':'待提交';return <span className={`badge ${text==='待提交'?'warm':text==='已反馈'?'positive':''}`}>{text}</span>}
export function AssignmentRow({assignment,teacher=false}:{assignment:AssignmentDetail;teacher?:boolean}){return <div className="assignment-row"><span className="row-icon"><FileText size={20}/></span><div className="assignment-row-copy"><small>{assignment.course_name}</small><h3>{assignment.title}</h3><p>{date(assignment.deadline)} 截止<span>·</span>{assignment.require_report&&'报告'}{assignment.require_report&&assignment.require_code&&' + '}{assignment.require_code&&'代码'}</p></div>{teacher?<span className="badge">{assignment.status==='draft'?'草稿':assignment.status==='closed'?'已关闭':'进行中'}</span>:<Badge assignment={assignment}/>}<a className="row-link" href={`/assignments/${assignment.id}`}>查看作业<ArrowUpRight size={16}/></a></div>}
export function DashboardPage({user,courses,assignments}:{user:UserSummary;courses:CourseSummary[];assignments:AssignmentDetail[]}){
  const student=user.role==='student',pending=assignments.filter(a=>!a.my_submission&&a.status==='open'),submitted=assignments.filter(a=>a.my_submission),published=assignments.filter(a=>a.my_submission?.grade?.published_at)
  const stats=student?[{name:'在学课程',value:courses.filter(c=>c.status==='active').length,Icon:BookOpen,detail:'保持好奇，持续学习'},{name:'待交作业',value:pending.length,Icon:Clock3,detail:'留意每一份作业的截止时间'},{name:'已交作业',value:submitted.length,Icon:ClipboardList,detail:'每次提交都保留独立版本'},{name:'收到反馈',value:published.length,Icon:CheckCircle2,detail:'查看老师发布的批改意见'}]:[{name:'管理课程',value:courses.length,Icon:BookOpen,detail:'你的教学课程'},{name:'全部作业',value:assignments.length,Icon:ClipboardList,detail:'已保存的作业安排'},{name:'开放提交',value:assignments.filter(a=>a.status==='open').length,Icon:Clock3,detail:'学生可以提交或重交'},{name:'课程学生',value:courses.reduce((n,c)=>n+c.student_count,0),Icon:CheckCircle2,detail:'各课程选课人数之和'}]
  return <><div className="page-heading"><div><p className="eyebrow">你的学习，一目了然</p><h1>你好，{user.display_name}</h1><p className="muted">{student?'今天也向前一步。这里是你的课程、作业与学习反馈。':'课程、作业与学生反馈，在这里有序连接。'}</p></div><a className="button secondary" href="/assignments">{student?'查看待交作业':'管理作业'}<ArrowUpRight size={17}/></a></div><section className="dashboard-hero"><div><span className="hero-caption">每一份努力都有回响</span><h2>{student?'每一次练习，\n都向前一步。':'让作业有序，\n让反馈及时。'}</h2><p>{student?`你有 ${pending.length} 份作业等待完成。留出思考的时间，\n让每一次提交都成为新的进步。`:'从清晰的要求开始，以认真的反馈结束。\n把教学的每一个环节，安排得井井有条。'}</p><a href="/assignments">{student?'开始今天的学习':'查看作业安排'}<ArrowRight size={18}/></a></div><div className="hero-art" aria-hidden="true"><div className="hero-paper paper-one"><span>COURSEWORK</span><div className="art-lines"/><div className="art-lines small"/><div className="art-check"><CheckCircle2 size={26}/></div></div><div className="hero-paper paper-two"><BookOpen size={35}/><small>记录 · 思考 · 成长</small></div><span className="hero-art-dot"/></div></section><div className="stats-grid">{stats.map(({name,value,Icon,detail})=><section className="stat-card" key={name}><div><span>{name}</span><Icon size={19}/></div><strong>{value.toString().padStart(2,'0')}</strong><small>{detail}</small></section>)}</div><div className="dashboard-bottom"><section className="panel"><div className="section-heading"><h2>{student?'近期作业':'作业安排'}<span>{assignments.length}</span></h2><a href="/assignments">查看全部<ArrowRight size={15}/></a></div>{assignments.length?assignments.slice(0,4).map(a=><AssignmentRow key={a.id} assignment={a} teacher={!student}/>):<div className="empty">还没有作业，新的安排会显示在这里。</div>}</section><section className="panel learning-note"><span className="eyebrow">学习备忘</span><BookOpen size={28}/><h2>先理解，<br/>再动手。</h2><p>读清作业要求，保留完整报告和源码。遇到问题时，记录你的思路与尝试。</p><div className="note-footer">一份好作业，从认真开始。<ArrowUpRight size={17}/></div></section></div></>
}
