# Generated by Django 5.2.17 on 2026-10-03 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('open', '开放提交'), ('closed', '已关闭')], default='draft', max_length=10)),
                ('deadline', models.DateTimeField()),
                ('allow_late', models.BooleanField(default=False)),
                ('require_report', models.BooleanField(default=True)),
                ('require_code', models.BooleanField(default=True)),
                ('total_score', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('template_revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='classroom.course')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('request_id', models.UUIDField()),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('deadline_snapshot', models.DateTimeField()),
                ('is_late', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='assignments.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('report', '报告'), ('code', '代码')], max_length=10)),
                ('original_name', models.CharField(max_length=240)),
                ('storage_key', models.CharField(max_length=100, unique=True)),
                ('size_bytes', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('extraction_status', models.CharField(default='pending', max_length=20)),
                ('extracted_text', models.TextField(blank=True)),
                ('locations', models.JSONField(default=list)),
                ('extraction_note', models.TextField(blank=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='assignments.submission')),
            ],
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('total_score__gt', 0)), name='positive_total_score'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('require_report', True), ('require_code', True), _connector='OR'), name='one_category_required'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('assignment', 'student', 'version'), name='unique_submission_version'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('student', 'request_id'), name='unique_submission_request'),
        ),
    ]
